### ISSUE TITLE
issue on ng serve

### ISSUE THREAD

**Issue by ietuday** [becompany/angular2-rss-reader-tutorial#5]
After npm install, when i fire ng serve it shows fokkowing error

The "@angular/compiler-cli" package was not properly installed.
Error: The "@angular/compiler-cli" package was not properly installed.
    at Object.<anonymous> (/home/uday/Project/angular2-rss-reader-tutorial-master/node_modules/@ngtools/webpack/src/index.js:14:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/uday/Project/angular2-rss-reader-tutorial-master/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

**Comment by jpuerto** [comment]
By the error message, something was wrong installing the dependencies and therefore it is not able to resolve on build.

Please review the process and if the problem persists, write here the steps to reproduce. I can not reproduce the problem with current master branch.

**Comment by jpuerto** [comment]
Not reproducible.
